# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6b37af0678e75bc2b023303df171a9e5b168cff15dfa017afbb066d2d83e7016bff03a490af19b594c795ef29baa9205a4d239bf6fe1e6b0a733bcc543026ca

test:
  secret_key_base: acbe88452213737f9640f4272099a1c25aa688f4dcdef514b49436e5063cce7e3d211175eaccd4c495f7de62d6dc3938008f86a3fa6937753072a54db27aa618

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
